repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--exclude=/tests/"]
        additional_dependencies:
          - "pydantic"
          - "types-requests"
          - "fastapi"
          - "sqlmodel"

  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        types: [python]
        args: [--check]

  # - repo: local
  #   hooks:
  #     - id: isort
  #       name: isort
  #       entry: isort
  #       language: system
  #       types: [python]
  #       args: [--check, --profile=black]
