repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        types: [python]
        additional_dependencies:
        -   "pydantic==v2.6.2"
        -   "sqlmodel==0.0.16"
        args: ["--strict", "--ignore-missing-imports", "--config-file", "pyproject.toml" ]

  - repo: https://github.com/ambv/black
    rev: 22.8.0
    hooks:
      - id: black
        types: [python]
        args: [--check]


  #- repo: local
    #hooks:
      #- id: isort
        #name: isort
        #entry: isort
        #language: system
        #types: [python]
        #args: [--check]
